version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
